name: flutter_release
description: A tool for building, releasing, publishing and deploying Flutter apps.
version: 0.0.5
repository: https://github.com/Oberhauser-Dev/flutter_release

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  flutter_release:

dependencies:
  args: ^2.4.2
  flutter_to_debian: # ^1.0.0
    git:
      url: 'https://github.com/jeffrey0606/flutter_to_debian.git'
      ref: a48830b

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
