name: dart_release
description: A tool for building and publishing Dart apps, e.g. on GitHub, the Microsoft Store, Home Brew and Snap.
version: 0.2.0
repository: https://github.com/Oberhauser-Dev/dart_packages/tree/main/packages/dart_release

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  dart_release:

dependencies:
  args: ^2.4.2
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
